name: ampera_vision_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  injectable: ^2.5.0
  get_it: ^8.0.0
  freezed_annotation: ^2.4.4
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  equatable: ^2.0.7
  clipboard: ^0.1.3
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
